// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: collections.sql

package database

import (
	"context"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (name) VALUES (?) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateCollection(ctx context.Context, name string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection, name)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
