root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "tmp/req"
  cmd = "go build -o ./tmp/req ."
  delay = 1000
  exclude_dir = ["tmp", "testdata"]
  include_ext = ["go"]

[log]
  time = true
  main_only = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
