name: Go Build, Test, and Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Build
        run: go build ./...

      - name: Run Tests
        run: go test ./...

      - name: Check gofmt
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files need to be formatted:"
            echo "$UNFORMATTED"
            exit 1
          fi
