name: Go CI

on:
  push:
    branches:
      - main
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test-matrix:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Build
        run: go build ./...

      - name: Run Tests
        run: go test ./...

  coverage:
    name: Code Coverage 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Auto-format code and commit changes
        run: |
          gofmt -w .
          if [ -n "$(git status --porcelain)" ]; then
            echo "Formatting changes detected. Committing..."
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add .
            git commit -m "chore: auto-format Go code via gofmt"
            git push
          else
            echo "Code is already formatted. No changes needed."
